### ISSUE TITLE
Drag and drop functionality

### ISSUE THREAD

**Issue by wertos97** [mortuusars/PSQuickAssets#15]
Hi! Could you add an option to drag and drop files right into the PSQA window? I work with files in recurring folders and adding all of them one by one can get a little exhausting. Drag and drop would speed up my workflow significantly. Thanks!

**Comment by mortuusars** [comment]
Yes, that's a good idea, I think I can do that.

**Comment by mortuusars** [comment]
Added simple drag&drop in 1.1.1. 
Next update will have proper functionality - with ability of adding not only folders, but files too.
