### ISSUE TITLE
Preview size

### ISSUE THREAD

**Issue by wertos97** [mortuusars/PSQuickAssets#16]
The preview size adjustable in the settings would be helpful when working with low width images. Currently previews are scaled to a certain height so narrow images are hard to distinguish. A simple slider inside the settings would do the job just right. Thanks!
![image](https://user-images.githubusercontent.com/18363190/132194336-39a5f111-43d6-405b-a4fd-93763c6b34a6.png)

**Comment by mortuusars** [comment]
Fixed in 1.1.1
