### ISSUE TITLE
Forced 'middle of the screen' problem

### ISSUE THREAD

**Issue by wertos97** [mortuusars/PSQuickAssets#6]
Since the app is forced to show up on the middle of the screen, for me it is displayed right between my two monitors. It's hilarious but also kind of difficut to work with. Adding or removing a folder thus changing the app's dimensions fixes the problem.

![image](https://user-images.githubusercontent.com/18363190/127267262-83829404-0a10-47cb-bb02-6b0356b85aed.png)

**Comment by mortuusars** [comment]
"Fixed" in new release. Window can now be resized and moved. This is probably better than fiddling with automatic positioning :)
