### ISSUE TITLE
PSD and PSB support

### ISSUE THREAD

**Issue by wertos97** [mortuusars/PSQuickAssets#7]
Currently if I want to add my templates folder, that consists of psd and psb files, the app says 'No valid images in a folder'. Adding support for those extensions would be great.

Thank you for creating this app. I didn't know I need such a tool that much <3

**Comment by mortuusars** [comment]
Added in new release.
No thumbnails for PSD and PSB yet. Creating them from large files can be slow. I'll look into it sometime.

**Comment by wertos97** [comment]
Thanks! I know Adobe Bridge does thumbnail pretty well. Maybe there is a way to connect it to PSQA
